name: metricnet
channels:
  - aihabitat
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - archspec=0.2.5=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.1=openblas
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py39h06a4308_0
  - cffi=1.17.1=py39h15c3d72_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=pyh707e725_0
  - cmake=3.14.0=h52cb24c_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=24.11.3=py39hf3d152e_0
  - conda-build=25.5.0=py39hf3d152e_0
  - conda-index=0.6.1=pyhd8ed1ab_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cccl=12.8.90=0
  - cuda-cccl_linux-64=12.8.90=0
  - cuda-crt-dev_linux-64=12.8.61=0
  - cuda-crt-tools=12.8.61=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-dev_linux-64=12.8.90=0
  - cuda-cudart-static_linux-64=12.8.90=0
  - cuda-cudart_linux-64=12.8.90=0
  - cuda-cuobjdump=12.8.90=0
  - cuda-cupti=12.4.127=0
  - cuda-driver-dev_linux-64=12.8.90=0
  - cuda-libraries=12.4.1=0
  - cuda-nvcc=12.8.61=0
  - cuda-nvcc-dev_linux-64=12.8.61=0
  - cuda-nvcc-impl=12.8.61=0
  - cuda-nvcc-tools=12.8.61=0
  - cuda-nvcc_linux-64=12.8.61=0
  - cuda-nvdisasm=12.8.90=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvm-dev_linux-64=12.8.61=0
  - cuda-nvvm-impl=12.8.61=0
  - cuda-nvvm-tools=12.8.61=0
  - cuda-opencl=12.8.90=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.8=3
  - cudnn=9.8.0.87=cuda12.8
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - deprecated=1.2.13=py39h06a4308_0
  - distro=1.9.0=pyhd8ed1ab_1
  - evalidate=2.0.5=pyhe01879c_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - fmt=11.0.2=h07f6e7f_1
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.57.0=py39h9399b63_0
  - freetype=2.13.3=h4a9f257_0
  - frozendict=2.4.6=py39h8cd3c5a_0
  - fsspec=2024.12.0=py39h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - habitat-sim-mutex=1.0=headless_bullet
  - headless=2.0=0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39hf3d152e_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=20_linux64_openblas
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.13.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.9.90=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=20_linux64_openblas
  - liblief=0.16.6=h5888daf_0
  - libllvm14=14.0.6=hecde1de_4
  - libllvm19=19.1.7=he89c38a_1
  - libmamba=1.5.12=h49b8a8d_0
  - libmambapy=1.5.12=py39hfb3fdd1_0
  - libmlir19=19.1.7=hdb19cb5_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.8.90=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libtorch=2.5.1=gpu_cuda124_h7d9372d_202
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - lit=19.1.7=py39h06a4308_1
  - llvmlite=0.43.0=py39h6a678d5_1
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=hd590300_1001
  - magma=2.7.1=ha545f22_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mbedtls=3.6.3.1=h5888daf_0
  - menuinst=2.2.0=py39hf3d152e_0
  - minizip=4.0.3=hf59b114_0
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - msgpack-python=1.1.1=py39h74842e3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h29a9f33_1
  - nccl=2.21.5.1=ha515578_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - nomkl=3.0=0
  - nspr=4.36=h5888daf_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.60.0=py39h6a678d5_1
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - ocl-icd=2.3.2=h5eee18b_1
  - olefile=0.47=pyhd8ed1ab_1
  - openblas=0.3.25=pthreads_h7a3da1a_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.1=h7b32b05_0
  - opentelemetry-api=1.30.0=py39h06a4308_0
  - packaging=24.2=pyhd8ed1ab_2
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.0=py39h06a4308_0
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=py39h06a4308_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py-lief=0.16.6=py39hf88036b_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py39h8cd3c5a_2
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.7.2=py39ha2c6bb1_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-libarchive-c=5.3=pyhe01879c_0
  - python_abi=3.9=2_cp39
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h4bd325d_2
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtshadertools=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebengine=6.7.2=hcbda680_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - quaternion=2023.0.4=py39hf15bc26_0
  - readline=8.2=h5eee18b_0
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=py39h06a4308_1
  - rhash=1.4.3=hdbd6064_0
  - ripgrep=14.1.1=h8fae777_1
  - rpds-py=0.25.1=py39h20260ba_0
  - ruamel.yaml=0.18.14=py39h8cd3c5a_0
  - ruamel.yaml.clib=0.2.8=py39h8cd3c5a_1
  - scipy=1.13.1=py39heeff2f4_1
  - setuptools=75.8.0=py39h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.5.1=h5eee18b_2
  - smmap=3.0.5=pyh44b312d_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.14=h39e8969_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.5.1=py39_cu124
  - tornado=6.4.2=py39h8cd3c5a_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.13.0=h9fa5a19_1
  - typing_extensions=4.13.0=pyh29332c3_1
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.3.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - withbullet=2.0=0
  - wrapt=1.17.0=py39h5eee18b_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py39h8cd3c5a_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - blinker==1.9.0
      - comm==0.2.2
      - configargparse==1.7.1
      - dash==3.2.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - diffusers==0.11.1
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - frozenlist==1.5.0
      - gh==0.0.4
      - habitat-sim==0.3.3
      - huggingface-hub==0.25.2
      - imageio-ffmpeg==0.6.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - lightning-utilities==0.14.3
      - lmdb==1.6.2
      - matplotlib-inline==0.1.7
      - multidict==6.3.2
      - narwhals==2.2.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - open3d==0.19.0
      - opencv-python-headless==4.11.0.86
      - pandas==2.2.3
      - parso==0.8.4
      - pastel==0.2.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - plotly==6.3.0
      - poethepoet==0.10.0
      - pot==0.9.5
      - prettytable==3.16.0
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==5.29.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pyquaternion==0.9.9
      - pytorch-lightning==2.5.1
      - pyzmq==26.4.0
      - regex==2024.11.6
      - retrying==1.4.2
      - scikit-learn==1.6.1
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tomlkit==0.13.2
      - torch==2.6.0
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.7.0
      - torchsde==0.2.6
      - torchvision==0.21.0
      - traitlets==5.14.3
      - trampoline==0.1.2
      - triton==3.2.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - vit-pytorch==1.10.1
      - wandb==0.19.9
      - warmup-scheduler==0.3
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
